"""JSON export helpers for the assembled session.

The bundle format makes observed, inferred, annotated and hidden information
explicit, and records that no native project file was parsed.
"""

from __future__ import annotations

from . import graph_builder, observation_model
from .models import SCHEMA_VERSION, SessionEvidence, to_dict

# W3C PROV-O mapping. The session graph is a provenance graph in disguise:
# observed artifacts are primary-source entities, annotations are entities
# attributed to the producer, derived analyses were generated by tool
# activities, and hidden-state markers are an honest extension class
# (lsee:HiddenState) marking state PROV cannot attest because no evidence
# reaches it. Edge types map onto PROV relations as below.
PROV_EDGE_RELATIONS = {
    "contains_audio": "prov:hadMember",
    "infers_track": "prov:wasDerivedFrom",
    "has_descriptor": "prov:wasDerivedFrom",
    "linked_to_midi": "prov:wasDerivedFrom",
    "linked_to_score_part": "prov:wasDerivedFrom",
    "annotated_by": "prov:wasAttributedTo",
    "mentions_plugin": "prov:hadMember",
    "mentions_send": "prov:hadMember",
    "mentions_bus": "prov:hadMember",
    "compared_to_reference": "prov:wasInfluencedBy",
    "part_of_reconciliation": "prov:wasDerivedFrom",
    "part_of_comparison": "prov:wasDerivedFrom",
    "has_hidden_state": "lsee:hasHiddenState",
    "supports_recommendation": "prov:wasDerivedFrom",
}

PROV_OBSERVABILITY_TYPES = {
    "observed": "prov:PrimarySource",
    "inferred": "lsee:InferredEntity",
    "annotation": "lsee:UserAssertion",
    "derived": "prov:Entity",
    "hidden": "lsee:HiddenState",
}


def session_evidence_json(session: SessionEvidence) -> dict:
    return to_dict(session)


def graph_json(session: SessionEvidence) -> dict:
    export = graph_builder.build_graph_export(session)
    return {"nodes": export.nodes, "edges": export.edges, "metadata": export.metadata}


def descriptors_json(session: SessionEvidence) -> list:
    return to_dict(session.descriptors)


def recommendations_json(session: SessionEvidence) -> list:
    return to_dict(session.recommendations)


def hidden_state_json(session: SessionEvidence) -> list:
    return to_dict(session.hidden_state_markers)


def prov_json(session: SessionEvidence) -> dict:
    """A PROV-O-grounded JSON view of the session graph.

    Grounds the graph schema in W3C PROV-O *vocabulary* (in a bespoke JSON
    layout — this is not the W3C PROV-JSON serialization): entities carry
    their observability class as a type, derivations follow the edge mapping
    in ``PROV_EDGE_RELATIONS``, user annotations are attributed to the
    producer agent, and inferred/derived entities are attributed to the tool
    agent. Hidden-state markers use the honest extension class
    ``lsee:HiddenState`` — provenance for what the evidence cannot attest.
    """

    graph = graph_builder.build_graph_export(session)
    entities = {}
    attributions: list[dict] = []
    for node in graph.nodes:
        observability = node.get("observability", "derived")
        entities[f"lsee:{node['id']}"] = {
            "prov:label": node.get("label", node["id"]),
            "prov:type": PROV_OBSERVABILITY_TYPES.get(observability, "prov:Entity"),
            "lsee:node_type": node["type"],
            "lsee:observability": observability,
        }
        # Inferred/derived entities (and hidden-state markers) are products of
        # this tool; annotations are attributed to the producer via edges.
        if observability in ("inferred", "derived", "hidden"):
            attributions.append({
                "prov:entity": f"lsee:{node['id']}",
                "prov:agent": "lsee:explorer",
                "lsee:basis": "generated_by_tool",
            })

    relations: dict[str, list[dict]] = {}
    for e in graph.edges:
        relation = PROV_EDGE_RELATIONS.get(e["type"], "prov:wasInfluencedBy")
        entry = {
            "prov:entity": f"lsee:{e['target']}",
            "prov:source": f"lsee:{e['source']}",
            "lsee:edge_type": e["type"],
        }
        if relation == "prov:wasAttributedTo":
            attributions.append({
                "prov:entity": f"lsee:{e['target']}",
                "prov:agent": "lsee:producer",
                "lsee:edge_type": e["type"],
            })
        else:
            relations.setdefault(relation, []).append(entry)

    return {
        "prefix": {
            "prov": "http://www.w3.org/ns/prov#",
            "lsee": "https://github.com/ColonelKernel/LogicSessionStateExplorer#",
        },
        "agent": {
            "lsee:producer": {"prov:type": "prov:Person",
                              "prov:label": "Producer (user-provided annotations)"},
            "lsee:explorer": {"prov:type": "prov:SoftwareAgent",
                              "prov:label": "Logic Session Evidence Explorer"},
        },
        "entity": entities,
        "wasAttributedTo": attributions,
        "relations": relations,
        "note": (
            "lsee:HiddenState entities record session state that no available "
            "evidence attests; they are deliberate extensions, not PROV-O terms."
        ),
    }


def full_bundle(session: SessionEvidence) -> dict:
    """Assemble the complete research bundle described in the spec."""

    graph = graph_builder.build_graph_export(session)
    return {
        "schema_version": SCHEMA_VERSION,
        "session_evidence": to_dict(session),
        "graph": {
            "nodes": graph.nodes,
            "edges": graph.edges,
            "metadata": graph.metadata,
        },
        "descriptors": to_dict(session.descriptors),
        "hidden_state_markers": to_dict(session.hidden_state_markers),
        "recommendations": to_dict(session.recommendations),
        "warnings": list(session.warnings),
        "export_metadata": {
            "daw": session.daw_name,
            "mode": "evidence_based",
            "native_project_parsed": False,
            "observation_model_version": observation_model.OBSERVATION_MODEL_VERSION,
        },
    }
